package org.nutz.dao.enhance.registrar.factory;

import org.nutz.dao.Dao;
import org.nutz.dao.enhance.config.DaoEnhanceConstant;
import org.nutz.dao.enhance.config.DaoProperties;
import org.nutz.dao.enhance.factory.DaoFactory;
import org.nutz.dao.enhance.holder.AutoCreateTableHolder;
import org.nutz.dao.impl.NutDao;
import org.nutz.dao.util.Daos;
import org.nutz.ioc.Ioc;

import javax.sql.DataSource;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Optional;
import java.util.Set;

/**
 * @author 黄川 2020/12/16
 * 默认实现
 */
public class DefaualtNutDaoFactory implements DaoFactory {
    /**
     * 数据源缓存
     */
    private final HashMap<String, Dao> daoCatche = new HashMap<>();

    private final Ioc ioc;

    private final DaoProperties daoProperties;

    public DefaualtNutDaoFactory(Ioc ioc, DaoProperties daoProperties) {
        this.ioc = ioc;
        this.daoProperties = daoProperties;
    }

    @Override
    public Dao getDao() {
        return this.getDao(DaoEnhanceConstant.DEFAUALT_DATASOURCE_KEY);
    }

    @Override
    public Dao getDao(String dataSource) {
        return daoCatche.get(dataSource);
    }

    /**
     * 初始化
     */
    public void init() {
        // 默认数据源
        final DataSource dataSource = this.ioc.get(DataSource.class);
        daoCatche.put(DaoEnhanceConstant.DEFAUALT_DATASOURCE_KEY, new NutDao(dataSource));
        // 多数据源
        final String[] names = this.ioc.getNamesByType(DataSource.class);
        Arrays.stream(names).filter(dsName -> !daoCatche.containsKey(dsName)).forEach(dsName ->
                daoCatche.put(dsName, new NutDao(this.ioc.get(DataSource.class)))
        );
        this.autoGenerateDdl();
    }

    /**
     * 自动建表
     */
    public void autoGenerateDdl() {
        final HashMap<String, Set<Class<?>>> dataSourceEntityClassMapping = AutoCreateTableHolder.getDataSourceEntityClassMapping();
        Optional.ofNullable(dataSourceEntityClassMapping).ifPresent(stringSetHashMap -> {
            stringSetHashMap.forEach((dataSource, classes) -> {
                final Dao dao = this.getDao(dataSource);
                classes.parallelStream().forEach(tableEntityClass -> Daos.createTablesInPackage(dao, tableEntityClass, false));
                classes.parallelStream().forEach(tableEntityClass ->
                        Daos.migration(dao,
                                tableEntityClass,
                                daoProperties.isMigrationAdd(),
                                daoProperties.isMigrationDel(),
                                daoProperties.isMigrationCheckIndex()));
            });
            AutoCreateTableHolder.destroy();
        });

    }

}
