package org.nutz.spring.boot.dao.spring.ddl;

import org.nutz.spring.boot.dao.factory.DaoFactory;

/**
 * @author 黄川 huchuc@vip.qq.com
 */
public class AutoGenerateDDLConfigurer {

    private DaoFactory daoFactory;

}
