package org.nutz.dao.spring.boot.ddl;

import lombok.RequiredArgsConstructor;
import org.nutz.dao.enhance.config.DaoProperties;
import org.nutz.dao.enhance.factory.DaoFactory;
import org.nutz.dao.enhance.method.holder.AutoCreateTableHolder;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

/**
 * @author 黄川 huchuc@vip.qq.com
 * 自动建表
 */
@Component
@RequiredArgsConstructor
public class DefaualtAutoGenerate implements CommandLineRunner {

    private final DaoProperties nutzDaoProperties;
    private final DaoFactory daoFactory;

    @Override
    public void run(String... args) {
        AutoCreateTableHolder.autoGenerateDdl(daoFactory, nutzDaoProperties);
    }


}
